# Generated by Django 4.2.4 on 2023-08-16 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UI_ELEMENTS', '0003_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
