# Generated by Django 4.2.3 on 2023-08-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0002_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default='<function uuid4 at 0x0000015218A3F060>', editable=False, primary_key=True, serialize=False),
        ),
    ]
