# Generated by Django 4.2.3 on 2023-08-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0007_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
