# Generated by Django 4.2.4 on 2023-08-17 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTS', '0021_banner_alter_product_variant_product'),
        ('USERS', '0010_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='PRODUCTS.product_variant'),
        ),
    ]
