# Generated by Django 4.2.4 on 2023-08-17 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0011_alter_cartitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='quantity',
            new_name='count',
        ),
    ]
