# Generated by Django 4.2.4 on 2023-08-17 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0014_alter_cartitem_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='product_variant',
        ),
    ]
