# Generated by Django 4.2.4 on 2023-08-17 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0017_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='updated_at',
        ),
    ]
