# Generated by Django 4.2.4 on 2023-08-17 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0020_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='product_variant',
        ),
    ]
