# Generated by Django 4.2.4 on 2023-08-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0022_alter_cartitem_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
