# Generated by Django 4.2.4 on 2023-08-19 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0024_cartitem_total_actual_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='total_discount_price',
            new_name='total_selling_price',
        ),
    ]
