# Generated by Django 4.2.4 on 2023-08-23 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTS', '0022_rename_discount_price_product_variant_selling_price'),
        ('USERS', '0026_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='product_variant',
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='PRODUCTS.product'),
        ),
    ]
