# Generated by Django 4.2.4 on 2023-08-23 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTS', '0022_rename_discount_price_product_variant_selling_price'),
        ('USERS', '0027_remove_wishlistitem_product_variant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='PRODUCTS.product'),
        ),
    ]
