# Generated by Django 4.2.4 on 2023-08-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0029_useraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
    ]
