# Generated by Django 4.2.4 on 2023-09-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0031_order_alter_useraddress_gender_orderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_actual_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='total_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='total_selling_price',
            field=models.IntegerField(default=0),
        ),
    ]
