# Generated by Django 4.2.4 on 2023-09-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0032_cart_total_actual_price_cart_total_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total_discount_price',
            field=models.IntegerField(default=0),
        ),
    ]
