# Generated by Django 4.2.4 on 2023-09-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0033_cartitem_total_discount_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='total_discount_price',
        ),
        migrations.AddField(
            model_name='cart',
            name='total_discount_price',
            field=models.IntegerField(default=0),
        ),
    ]
