# Generated by Django 4.2.4 on 2023-09-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0034_remove_cartitem_total_discount_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='a', max_length=50),
        ),
    ]
