# Generated by Django 4.2.4 on 2023-09-06 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTS', '0022_rename_discount_price_product_variant_selling_price'),
        ('USERS', '0037_remove_orderitem_cart_item_orderitem_product_variant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_Variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRODUCTS.product_variant'),
        ),
    ]
