# Generated by Django 4.2.4 on 2023-09-06 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0038_alter_orderitem_product_variant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_Variant',
            new_name='product_variant',
        ),
    ]
