# Generated by Django 4.2.4 on 2023-09-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0039_rename_product_variant_orderitem_product_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='district',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='post',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
