# Generated by Django 4.2.4 on 2023-09-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0041_useraddress_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='district',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='post',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
