# Generated by Django 4.2.4 on 2023-09-09 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTS', '0022_rename_discount_price_product_variant_selling_price'),
        ('USERS', '0045_alter_review_product_alter_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='star',
            new_name='rating',
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='PRODUCTS.product'),
        ),
    ]
