# Generated by Django 4.2.4 on 2023-09-11 13:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0048_alter_review_order_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewImages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='review images/')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_images', to='USERS.review')),
            ],
        ),
    ]
