# Generated by Django 4.2.4 on 2023-09-12 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTS', '0022_rename_discount_price_product_variant_selling_price'),
        ('USERS', '0050_rename_reviewimages_reviewimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='PRODUCTS.product_variant'),
        ),
    ]
