# Generated by Django 4.2.4 on 2023-09-14 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0052_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
