# Generated by Django 4.2.4 on 2023-09-21 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTS', '0026_alter_coupon_details'),
        ('USERS', '0053_delete_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='order_item',
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='PRODUCTS.product'),
        ),
    ]
