# Generated by Django 4.2.4 on 2023-09-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0059_cart_coupon_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='final_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
