# Generated by Django 4.2.4 on 2023-09-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0060_cart_final_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='coupon_discount_price',
            new_name='coupon_discount',
        ),
        migrations.AddField(
            model_name='order',
            name='final_price',
            field=models.IntegerField(default=0),
        ),
    ]
