# Generated by Django 4.2.4 on 2023-10-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0061_rename_coupon_discount_price_order_coupon_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(default='failed', max_length=30),
        ),
    ]
