# Generated by Django 4.2.4 on 2023-10-02 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0064_orderitem_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
