# Generated by Django 4.2.4 on 2023-10-02 19:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTS', '0031_coupon_status'),
        ('USERS', '0065_delete_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='On the Way', max_length=30)),
                ('count', models.PositiveIntegerField(default=1)),
                ('total_actual_price', models.IntegerField(default=0)),
                ('total_selling_price', models.IntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='USERS.order')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='PRODUCTS.product_variant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
