# Generated by Django 4.2.4 on 2023-10-04 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0066_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='coupon_discount',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='final_price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total_discount_price',
        ),
    ]
