# Generated by Django 4.2.4 on 2023-10-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0067_remove_cart_coupon_discount_remove_cart_final_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon_discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='final_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='total_discount_price',
            field=models.IntegerField(default=0),
        ),
    ]
