# Generated by Django 4.2.4 on 2023-10-05 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0068_cart_coupon_discount_cart_final_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='coupon_discount',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='final_price',
        ),
    ]
