# Generated by Django 4.2.4 on 2023-10-07 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0070_cart_coupon_discount_cart_final_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
