# Generated by Django 4.2.4 on 2023-10-09 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0073_order_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_items',
        ),
    ]
