# Generated by Django 4.2.3 on 2023-08-02 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTS', '0002_alter_brand_uid_alter_category_uid_alter_product_uid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='uid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='uid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='uid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='uid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='uid',
            new_name='id',
        ),
    ]
