# Generated by Django 4.2.3 on 2023-08-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTS', '0003_rename_uid_brand_id_rename_uid_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product',
            field=models.ImageField(blank=True, null=True, upload_to='product/'),
        ),
    ]
