# Generated by Django 4.2.3 on 2023-08-02 13:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTS', '0008_remove_productimage_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.CreateModel(
            name='Sub_Category',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_category_name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='subcategory/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRODUCTS.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
