# Generated by Django 4.2.3 on 2023-08-02 16:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTS', '0009_alter_category_options_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=100)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRODUCTS.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
