# Generated by Django 4.2.3 on 2023-08-02 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTS', '0010_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='PRODUCTS.category'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
