# Generated by Django 4.2.3 on 2023-08-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTS', '0013_alter_product_sub_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sub_category',
            options={'verbose_name_plural': 'sub categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
    ]
