# Generated by Django 4.2.4 on 2023-08-15 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTS', '0015_alter_brand_id_alter_category_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='brand_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='model_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sub_category',
            old_name='sub_category_name',
            new_name='name',
        ),
    ]
