# Generated by Django 4.2.4 on 2023-08-15 18:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('UI_ELEMENTS', '0003_color'),
        ('PRODUCTS', '0017_remove_product_actual_price_remove_product_image1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Variant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actual_price', models.IntegerField()),
                ('discount_price', models.IntegerField()),
                ('discount_percentage', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='UI_ELEMENTS.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varints', to='PRODUCTS.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVarientImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_images', to='PRODUCTS.product_variant')),
            ],
        ),
    ]
