# Generated by Django 4.2.4 on 2023-08-16 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTS', '0018_product_variant_productvarientimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_variant',
            name='description',
        ),
    ]
