# Generated by Django 4.2.4 on 2023-08-16 03:38

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTS', '0019_remove_product_variant_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_variant',
            name='color_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product_variant',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None),
        ),
    ]
