# Generated by Django 4.2.4 on 2023-08-19 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTS', '0021_banner_alter_product_variant_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_variant',
            old_name='discount_price',
            new_name='selling_price',
        ),
    ]
