# Generated by Django 4.2.4 on 2023-09-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTS', '0025_coupon_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='details',
            field=models.CharField(max_length=200),
        ),
    ]
