# Generated by Django 4.2.4 on 2023-11-27 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTS', '0031_coupon_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PRODUCTS.product_variant'),
        ),
    ]
