# Generated by Django 4.2.4 on 2023-11-28 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTS', '0033_alter_banner_variant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='variant',
            new_name='product',
        ),
    ]
